#!/usr/bin/env python

import time
import struct
import colorsys

try:
    from PySide import QtCore, QtGui
except ImportError:
    print("[error] sudo apt-get install python-pyside")
    import sys; sys.exit(1)

try:
    import gladys
except ImportError:
    print("[error] install gladys [and setup PYTHONPATH]")
    import sys; sys.exit(1)

def float_to_rgb(hue):
    assert(0.0 <= hue <= 1.0)
    # from blue to red (instead of red to red)
    # aka from 240 to 0 instead of 0 to 360 degrees (HSV)
    hue = (1 - hue) / 1.5
    return colorsys.hsv_to_rgb(hue, 1, 1)

def uint_to_rgb(hue):
    r, g, b = float_to_rgb(hue / 255.0)
    return int(r*255), int(g*255), int(b*255)

GRAY_COLORTABLE = [QtGui.QColor(i, i, i).rgb()          for i in range(256)]
HSVH_COLORTABLE = [QtGui.QColor(*uint_to_rgb(i)).rgb()  for i in range(256)]

class ImageLabel(QtGui.QLabel):
    def __init__(self):
        QtGui.QLabel.__init__(self)
        self.path = QtGui.QPolygonF()
    def set_image(self, image):
        self.setPixmap(QtGui.QPixmap.fromImage(image))
    def paint_path(self, path):
        self.path = QtGui.QPolygonF()
        for x, y in path:
            self.path.append(QtCore.QPointF(x, y))
        self.repaint()
    def paintEvent(self, event):
        QtGui.QLabel.paintEvent(self, event)
        painter = QtGui.QPainter(self)
        painter.setPen(QtGui.QPen(QtCore.Qt.black, 2))
        painter.drawPoints(self.path)

class MainWindow(QtGui.QMainWindow):
    def __init__(self, argv):
        super(MainWindow, self).__init__()
        self.ng = self.start = self.end = None

        # image viewer
        self.image_label = ImageLabel()
        self.setCentralWidget(self.image_label)

        self.setWindowTitle("Gladysplay")
        self.resize(200, 200)

        self.fregion = argv[1]
        self.frobot = argv[2]

        print("===============================\n"
              "  Welcome to Gladys display !\n"
              "===============================\n\n"
              "Actions\n"
              "-------\n"
              " - Click     = select start and end points\n"
              " - Space     = start search path\n"
              " - C         = clear start and end points\n"
              " - N         = switch {region,weight} view\n"
              " - L         = switch {gray,hsvh} LUT\n"
              " - Escape    = quit\n")

        # key bindings
        self._bindings = {}
        self.bind(QtCore.Qt.Key_Escape, self.close)
        self.bind(QtCore.Qt.Key_Space,  self.start_search)
        self.bind(QtCore.Qt.Key_C,      self.clear_points)
        self.bind(QtCore.Qt.Key_N,      self.switch_raster)
        self.bind(QtCore.Qt.Key_L,      self.switch_lut)

        self._raster = ""
        self._images = {}
        self._region = None
        self._weight = None
        self._lut    = {
                'HSVH': HSVH_COLORTABLE,
                'GRAY': GRAY_COLORTABLE,
            }
        print("Loading graph...")
        # start to load the graph in 50ms
        QtCore.QTimer.singleShot(50, self.load_nav_graph)

    def i8u2rgb(self, width, height, image8u):
        """ Convert a grayscale image to RGB """
        # Convert from list(uint8_t) to bytes() [TODO find memoryview in bpy]
        buff = struct.pack('%iB'%len(image8u), *image8u)
        assert(len(buff) == width * height)
        # QImage does not holds the buffer, it is valid only in this scope (!)
        image = QtGui.QImage(buff, width, height, width, QtGui.QImage.Format_Indexed8)
        # Set image lookup table (LUT) / PySide.QtGui.QImage.setColorTable()
        # http://qt-project.org/doc/qt-5.1/qtgui/qimage.html#setColorTable
        image.setColorTable(HSVH_COLORTABLE)
        # Return a copy (buffer copied, so no need to hold it ourself)
        return image.copy()

    def setup_next_region(self):
        if not self._weight:
            return -1
        if not self._region:
            t_start = time.time()
            region_map = self._weight.get_region()
            self._region = region_map.get_bands_as_uchar()
            print("Got the region bands (%.3fs)" \
                % (time.time() - t_start) )
        names = self._region.keys()
        # Select the next region layer to show
        if self._raster not in names:
            self._raster = names[0]
        else:
            index = names.index(self._raster) + 1
            if index < len(self._raster):
                self._raster = names[index]
            else:
                return -1
        if self._raster not in self._images:
            self._images[self._raster+".lut"] = "HSVH"
            self._images[self._raster] = self.i8u2rgb(
                    self._weight.get_width(),
                    self._weight.get_height(),
                    self._region[self._raster] )

    def setup_weight(self):
        self._raster = "weight"
        if self._raster not in self._images:
            self._weight = self.ng.get_map() # saving weight-map to get region
            weight_band = self._weight.get_weight_band_uchar()
            self._images[self._raster+".lut"] = "HSVH"
            self._images[self._raster] = self.i8u2rgb(
                    self._weight.get_width(),
                    self._weight.get_height(),
                    weight_band)

    def switch_raster(self):
        t_start = time.time()

        if self.setup_next_region() == -1:
            self.setup_weight()

        # Display the image
        self.image_label.set_image( self._images[self._raster] )
        print("Display %s (%.3fs)" % (self._raster, time.time() - t_start) )

    def switch_lut(self):
        lname = self._images[self._raster+".lut"]
        names = self._lut.keys()
        index = names.index(lname)
        index = 0 if index == len(names) - 1 else index + 1
        lname = names[index]
        print("Switching LUT %s for %s" % (lname, self._raster) )

        self._images[self._raster].setColorTable(self._lut[lname])
        self.image_label.set_image( self._images[self._raster] )
        self._images[self._raster+".lut"] = lname

    def load_nav_graph(self):
        t_start = time.time()
        self.ng = gladys.nav_graph(self.fregion, self.frobot)
        print("Graph loaded (%.3fs)" % (time.time() - t_start) )
        self.switch_raster()

    def update_path(self, path):
        self.image_label.paint_path(path)

    def search(self):
        if not self.ng:
            print("[error] not ready for search (no graph)")
            return

        print("Search a path between %s" % str([self.start, self.end]) )
        t_start = time.time()
        pp = self.ng.search(self.start, self.end)
        print("Got a path of %i points (%.3fs)" % ( len(pp), \
            (time.time() - t_start) ) )
        self.update_path(pp)
        self.start = self.end = None

    def bind(self, key, func):
        self._bindings[key] = func

    def start_search(self):
        if self.start and self.end:
            # start search in 50ms
            QtCore.QTimer.singleShot(50, self.search)
        else:
            print("select start and end points")

    def clear_points(self):
        self.start = self.end = None
        print("clear start and end")

    # PySide.QtGui.QWidget.keyPressEvent(event)
    def keyPressEvent(self, event):
        if event.key() in self._bindings:
            self._bindings[event.key()]()

    # PySide.QtGui.QWidget.mousePressEvent(event)
    def mousePressEvent(self, event):
        pose = event.pos()
        if not self.start:
            self.start = ( pose.x(), pose.y() )
            print("start = %s" % str(self.start) )
        if not self.end:
            self.end = ( pose.x(), pose.y() )
            if self.end == self.start:
                self.end = None
            else:
                print("end = %s" % str(self.end) )

def main(argv=[]):
    if len(argv) < 3:
        print("usage: %s region.tif robot.json"%argv[0])
        return 1
    app = QtGui.QApplication(argv)
    mww = MainWindow(argv)
    mww.show()
    return app.exec_()

if __name__ == '__main__':
    import sys
    sys.exit( main(sys.argv) )

