#!/usr/bin/env python

import json

try:
    from PySide import QtCore, QtGui
except ImportError:
    print("[error] sudo apt-get install python-pyside")
    import sys; sys.exit(1)

try:
    import gladys
except ImportError:
    print("[error] install gladys [and setup PYTHONPATH]")
    import sys; sys.exit(1)

def is_white(point, qimage):
    color = QtGui.QColor( qimage.pixel(*point) )
    for c in color.getRgbF():
        if c < 1.0:
            return False
    return True

def main(argv=[]):
    if len(argv) < 4:
        print("usage: %s geo.tif filter.png radius"%argv[0])
        return 1

    # get GeoTiff for scale info
    geotiff = gladys.gdal(argv[1])
    # get the filter for points
    ifilter = QtGui.QImage(argv[2])
    # get robot radius
    radius  = float(argv[3])

    width   = geotiff.get_width()
    height  = geotiff.get_height()
    scale_x = geotiff.get_scale_x()
    scale_y = geotiff.get_scale_y()
    xradius = int(radius/abs(scale_x))
    yradius = int(radius/abs(scale_y))

    points = []
    for i in range(xradius, width, xradius):
        for j in range(yradius, height, yradius):
            if is_white((i,j), ifilter):
                custom = gladys.point_pix2custom(geotiff, i, j)
                # test point in image (throw out of range if wrong)
                geotiff.index_custom(*custom)
                points.append(custom)

    print(json.dumps(points))

    return 0

if __name__ == '__main__':
    import sys
    sys.exit( main(sys.argv) )
